theme: jekyll-theme-minimal
title: Sid Sankhe
description: sid@manifoldtrading.com <br> <a href='https://scholar.google.com/citations?user=XzYf1JIAAAAJ&hl=en'>Google Scholar</a> <br> <a href='https://www.linkedin.com/in/sidharth-sankhe/'>LinkedIn</a>
logo: photo.png
